vesoft-inc/nebula-dashboard

config.json

Example Change port 8080 to 8090.

Mod:change config.json "gateway.target"

---

src/components/Charts/LineChart.tsx
src/components/DashboardCard/LineCard.tsx
src/pages/MachineDashboard/Detail/index.tsx
src/pages/MachineDashboard/index.tsx
src/pages/MetricDetail/index.tsx
src/store/models/machine.ts
src/utils/dashboard.ts

and make the serialize xAxis label

fix: chart timeline

---

src/components/Charts/LineChart.tsx

fix: update lineChart

---

src/components/MetricsFilterPanel/index.tsx
src/pages/MachineDashboard/Detail/index.tsx
src/pages/ServiceDashboard/Detail/index.tsx

fix: 2218,2344,2214,2327,2326,2216,2325,2321,2320,2301

---

src/pages/MachineDashboard/index.tsx
src/pages/ServiceDashboard/ServiceOverview/CustomServiceQueryPanel/index.tsx
src/utils/dashboard.ts

fix: some issues in 1230

---

src/components/TimeSelect/index.tsx

fix: timerange sync

---

src/pages/ServiceManage/PartitionInfo/index.tsx
src/store/models/nebula.ts

feat: some issue in 1230

---

src/components/DashboardCard/index.less
src/components/DashboardCard/index.tsx
src/components/Instruction/index.less
src/pages/MachineDashboard/index.tsx
src/utils/promQL.ts

- fix #2338
- fix #2297
- fix #2226

fix: issues

---

src/components/MetricsFilterPanel/index.tsx

feat: fix some issues

---

src/utils/metric.ts
src/utils/promQL.ts

feat: change 1m to 15s

---

src/utils/promQL.ts

fix: use 1m

---

src/pages/ServiceDashboard/Detail/index.tsx
src/pages/ServiceDashboard/ServiceOverview/CustomServiceQueryPanel/index.tsx
src/store/models/service.ts
src/utils/metric.ts
src/utils/service.ts

fix: service overview use sum

---

src/config/locale/zh-CN/description.json

feat: update info

---

src/components/Charts/LineChart.tsx

fix: add chartRef

---

src/components/Charts/LineChart.tsx
src/config/locale/zh-CN/rules.json

1230bugfix

---

src/pages/ServiceManage/Overview/index.tsx
src/store/models/nebula.ts

fix: overview fetching job bug

---

src/components/MetricsFilterPanel/index.module.less
src/components/MetricsFilterPanel/index.tsx
src/pages/MachineDashboard/Cards/DiskCard.tsx
src/pages/MachineDashboard/index.tsx
src/pages/ServiceDashboard/ServiceOverview/index.tsx
src/pages/ServiceDashboard/index.tsx
src/store/models/machine.ts
src/store/models/service.ts
src/utils/promQL.ts

fix: some issues

---

src/config/locale/en-US/metric_description.json
src/config/locale/zh-CN/metric_description.json

feat: metric related bugfix

---

src/utils/index.ts

feat:  add localStorageUtils

---

package.json

feat: use 3.4.0 version

---

vendors/config-release.yaml

chore: udpdate community auto deploy

---

.github/workflows/nightly.yml

chore: update workflow

---

scripts/setEventTracking.sh

chore: update event tracking

---

src/components/Charts/LineChart.tsx
src/utils/promQL.ts

feat: add status line chart

---

src/pages/ServiceManage/Overview/index.tsx
src/store/models/nebula.ts

fix: remove currentSpace session

---

src/pages/ServiceManage/LeaderDistribution/index.tsx
src/utils/dashboard.ts

fxi: miss key

---

src/store/models/service.ts
src/utils/metric.ts

fix: status label

---

src/store/models/machine.ts
src/store/models/metric.ts
src/store/models/service.ts
src/utils/dashboard.ts
src/utils/metric.ts
src/utils/promQL.ts

fix: add latency auto

---

src/pages/ServiceManage/Overview/index.tsx

fix: remove nebulaconnect flag

---

src/components/DashboardCard/LineCard.tsx
src/pages/ServiceManage/Overview/index.tsx
src/utils/metric.ts

fix: some bugs in cluster overview

---

src/components/Charts/LineChart.tsx

fix: add brush api

---

src/components/DashboardCard/LineCard.tsx

fix: add linecard onref hook

---

src/config/locale/en-US/device.json
src/config/locale/zh-CN/device.json
src/config/locale/zh-CN/metric_description.json
src/pages/ServiceDashboard/OverviewTable.tsx
src/pages/ServiceDashboard/ServiceOverview/index.tsx
src/utils/promQL.ts

feat: update service monitor overview

---

src/components/Charts/LineChart.tsx
src/components/MetricCard/index.tsx
src/pages/MachineDashboard/index.tsx
src/pages/ServiceDashboard/ServiceOverview/index.tsx

fix: add community chart hook

---

README.md

Consistent with the documentation on the documentation site

Update README version alignment

---

src/components/DashboardCard/index.tsx
src/components/TimeSelect/index.tsx
src/config/locale/en-US/component.json
src/config/locale/zh-CN/component.json
src/pages/MachineDashboard/Cards/DiskCard.tsx
src/pages/MachineDashboard/MachinePanelDetail/index.module.less
src/pages/MachineDashboard/MachinePanelDetail/index.tsx
src/pages/MachineDashboard/NodeResourceOverview/index.tsx
src/pages/MachineDashboard/index.tsx
src/utils/dashboard.ts
src/utils/promQL.ts

feat: add machine monitor detail panel

---

src/components/TimeSelect/index.tsx
src/utils/dashboard.ts

feat: add memory usage utilization panel

---

src/pages/MetricDetail/index.tsx
src/pages/ServiceDashboard/Detail/index.module.less
src/pages/ServiceDashboard/Detail/index.tsx
src/pages/ServiceDashboard/ServiceOverview/index.tsx
src/utils/metric.ts

feat: add p95/p99 in latency

---

src/pages/ServiceManage/Overview/index.tsx

fix: remove fetch balance status

---

src/components/MetricsFilterPanel/index.module.less

feat: update css

---

src/pages/ServiceDashboard/OverviewTable.tsx

feat: fix bug when service exited

---

src/pages/MetricDetail/index.tsx
src/utils/promQL.ts

fix: line aggregate error

---

src/config/locale/en-US/device.ts
src/config/locale/zh-CN/device.ts
src/pages/MachineDashboard/NodeResourceOverview/index.module.less
src/pages/MachineDashboard/NodeResourceOverview/index.tsx
src/pages/ServiceDashboard/OverviewTable.tsx
src/pages/ServiceDashboard/index.module.less
src/utils/metric.ts

feat: fix bugs

---

src/pages/MachineDashboard/NodeResourceOverview/index.tsx
src/pages/ServiceDashboard/OverviewTable.tsx

fix: fix bugs

---

src/config/locale/en-US/metric_description.ts

fix: fix some bugs

---

src/pages/ServiceDashboard/ServiceOverview/index.tsx

feat: remove view icon

---

package.json
src/components/ModalWrapper/index.tsx

fix: update antd

---

src/components/ModalWrapper/index.tsx

fix: modal wrapper auto destroy

---

src/config/locale/en-US/common.ts
src/config/locale/zh-CN/common.ts
src/pages/ServiceManage/Overview/index.tsx
src/pages/ServiceManage/ServiceInfo/index.tsx

- fix https://github.com/vesoft-inc/nebula-dashboard-ent/issues/2979

fix: update Service Info name

---

src/components/DashboardCard/LineCard.tsx
src/pages/MetricDetail/index.tsx
src/utils/dashboard.ts

feat: update cluster overview

---

src/pages/MachineDashboard/Cards/DiskCard.tsx

fix: disk card error

---

src/components/Charts/SpaceChart.less
src/components/DashboardCard/index.less
src/components/MetricCard/index.tsx
src/pages/MachineDashboard/Cards/DiskCard.tsx
src/pages/ServiceDashboard/ServiceOverview/index.tsx
src/utils/interface.ts
src/utils/promQL.ts

feat: update monitor dashboard

---

src/components/Charts/SpaceChart.less
src/pages/MachineDashboard/Cards/DiskCard.tsx

feat: fix some bugs about customize monitor

---

src/utils/dashboard.ts

fix: xAxis label miss

---

src/pages/MachineDashboard/Cards/DiskCard.tsx

feat: update disk usage promql

---

src/components/Charts/SpaceChart.less
src/components/Charts/SpaceChart.tsx
src/pages/MachineDashboard/Cards/DiskCard.tsx

fix: fix some issues

---

src/utils/interface.ts
src/utils/metric.ts

fix: consider space level metircs, and modify menu items

---

src/utils/dashboard.ts
src/utils/interface.ts

fix: add space metric

---

src/components/Charts/LineChart.tsx
src/components/DashboardCard/LineCard.tsx
src/pages/ServiceManage/Overview/index.tsx
src/utils/dashboard.ts

fix: add timeraneg scope in linechart

---

src/components/Charts/LineChart.tsx
src/components/DashboardCard/LineCard.tsx
src/components/MetricsFilterPanel/index.module.less

V3.6.0 dev

---

src/utils/interface.ts
src/utils/metric.ts

fix: add getServiceMetricOptions methds

---

src/pages/MachineDashboard/Cards/DiskCard.tsx
src/store/models/metric.ts
src/utils/dashboard.ts
src/utils/interface.ts
src/utils/metric.ts

fix: add some common methods

---

src/components/Charts/LineChart.tsx
src/components/DashboardCard/LineCard.tsx
src/utils/dashboard.ts

fix: calcScaleOption max value in percentage type

---

src/pages/ServiceManage/Overview/index.tsx

feat: support zone

---

src/pages/ServiceManage/Overview/index.tsx

fix: balance remove ngql

---

src/components/Charts/RingProgressChart.tsx
src/pages/ServiceManage/Overview/index.tsx
src/utils/interface.ts

fix: some issue

---

src/components/Icon/index.less
src/components/Icon/index.tsx

feat: add spin in Icon component

---

src/components/ModalWrapper/index.tsx

V3.7.0 dev

---

src/components/ModalWrapper/index.tsx

feat: update modalwrapper

---

src/utils/dashboard.ts
src/utils/interface.ts
src/utils/metric.ts

feat: update metrics filterServiceMetrics
